services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: images_reshaper_bot
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    restart: always
    networks:
      - app_network

  webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    container_name: images_reshaper_webapp
    volumes:
      - ./src:/app/src
      - ./static:/app/static
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge