services:
  images_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: images_reshaper_bot
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: always 