services:
  bot:
    build:
      context: .
      dockerfile: telegram_bot/Dockerfile
    container_name: images_reshaper_bot
    volumes:
      - ./telegram_bot/src:/app/src
      - ./shared:/app/shared
      - ./temp:/app/temp
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    restart: always
    networks:
      - app_network

  webapp:
    build:
      context: .
      dockerfile: webapp/Dockerfile
    container_name: images_reshaper_webapp
    volumes:
      - ./webapp/src:/app/src
      - ./webapp/static:/app/static
      - ./shared:/app/shared
      - ./temp:/app/temp
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
